### ISSUE TITLE
Let getPayload() return an object or an array

### ISSUE THREAD

**Issue by sjimi** [iron-io/iron_worker_php#14]
Now the getPayload() only retrieves an object (or a string if it fails to parse the payload). Would it be possible to let the user decide wether it wants an object or an array like the json_decode function?

**Comment by nodesocket** [comment]
Just upgraded to `1.4.3` from `1.4.2` and previously `getPayload()` returned an object thus our workers expected objects. For example:

    $payload = getPayload();
    echo $payload->foobar

This change to returning an array BROKE :cry: :sob: all of our workers, and caused tasks to fail for about 30 minutes.

If you are going to make breaking changes, really you need to document it, and have big warnings in the README.md.

**Comment by nodesocket** [comment]
Here is the problem, you default `assoc` to true. This should default to false to prevent breaking changes.

https://github.com/iron-io/iron_worker_php/blob/master/IronWorker.class.php#L803

**Comment by sunloverz** [comment]
Thanks! We will fix that

**Comment by nodesocket** [comment]
I already changed my code

    $payload->foobar

to

    $payload['foobar']

You can leave it as an array, just you should make it VERY clear.

**Comment by sunloverz** [comment]
Or another way just pass false to get an object without changing all code

**Comment by nodesocket** [comment]
Just so I am clear, you aren't gong to revert this flag back to `assoc=false` are you?

**Comment by sunloverz** [comment]
Going to revert back, sent a pull request https://github.com/iron-io/iron_worker_ruby_ng/pull/212
