### ISSUE TITLE
Update iron-io/iron_core dependency

### ISSUE THREAD

**Issue by Sjimi** [iron-io/iron_worker_php#29]
Is it possible to update the `iron-io/iron_core` dependency for this pacakge to `1.*` version too? Just like in the `iron-io/iron_mq` package? Currently I run into trouble when I try to use both together.

**Comment by thousandsofthem** [comment]
Sure! For now you could use different branch of mq library

**Comment by Sjimi** [comment]
I don't think I can do that because I am using in with Laravel 5 so I need the newest branch `4.*` version of the `iron-io/iron_mq` package.

**Comment by jszobody** [comment]
Any update on this?

I have the same problem here. Laravel/Lumen 5.1 requires `iron-io/iron_mq` version `~2.0`, which requires `iron-io/iron_core` version `1.*`. 

Which means I can't use iron_worker in Laravel/Lumen 5.1 due to the old `iron-io/iron_core` dependency. =/

**Comment by thousandsofthem** [comment]
Hey! going to fix it in next 1-2 days

**Comment by thousandsofthem** [comment]
@jszobody @Sjimi version IronWorker 2.0 is out. could you try it?

**Comment by jszobody** [comment]
Looks good to me, thanks!
